name: Automated Tests

on:
  #   push:
  #     branches:
  #       - main
  workflow_dispatch:


jobs:
  # generate_csv:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     issues: read
  #     checks: write
  #     pull-requests: write
  #     # pull-requests: write
  #   strategy:
  #     fail-fast: false
  #   # steps:
  #   #   - name: Checkout repository
  #   #     uses: actions/checkout@v3
  #   #     with:
  #   #       token: ${{secrets.MY_GITHUB_TOKEN}}

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r -requirements.txt
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps chromium
      - name: Run Playwright tests
        continue-on-error: true

        # run: pytest test_kadai.py --browser-channel msedge --alluredir=allure-results
        run: pytest test_data_driven.py --browser-channel msedge --alluredir=allure-results


      # - name: Test Report Output
      #   uses: simple-elf/allure-report-action@v1.8
      #   if: always()
      #   # id: allure-report
      #   with:
      #     allure_results: allure-results
      #     gh_pages: gh-pages
      #     allure_report: allure-report
      #     allure_history: allure-history
      #     keep_reports: 20

      #   continue-on-error: true
      # - name: store allure results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: allure-report
      #     path: allure-report
      #     retention-days: 1

      # - name: Deploy report to Github Pages
      #   if: always()
      #   uses: peaceiris/actions-gh-pages@v2
      #   env:
      #     PERSONAL_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: allure-history
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.8
        if: always()
        id: allure-report
        with:
          allure_results: allure-results/
          gh_pages: gh-pages
          # allure_report: reports/allure-report
          allure_history: reports/allure-report
          keep_reports: 20
      # - name: Deploy Allure Report to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: reports/allure-report
      #     publish_branch: gh-pages
